[changelog]
header = """
# Changelog

"""
body = """
{%- macro remote_url() -%}
  https://github.com/SpyicyDev/macblock
{%- endmacro -%}

{% if version %}\
## [{{ version | trim_start_matches(pat="v") }}]({{ self::remote_url() }}/releases/tag/{{ version }}) - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
## [Unreleased]
{% endif %}\

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits %}
- {{ commit.message | split(pat="\n") | first | trim }}
{% endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = false
filter_unconventional = false
commit_parsers = [
  { message = "^(?i)feat", group = "Features" },
  { message = "^(?i)add", group = "Features" },
  { message = "^(?i)fix", group = "Bug Fixes" },
  { message = "^(?i)docs?", group = "Documentation" },
  { message = "^(?i)perf", group = "Performance" },
  { message = "^(?i)refactor", group = "Refactoring" },
  { message = "^(?i)test", group = "Testing" },
  { message = "^chore\\(release\\)", skip = true },
  { message = "^(?i)chore|^(?i)ci", group = "Miscellaneous" },
  { message = ".*", group = "Miscellaneous" },
]
filter_commits = false
tag_pattern = "v[0-9].*"
sort_commits = "newest"
